still progressing U-01

diff --git a/scripts/U-01 b/scripts/U-01
--- a/scripts/U-01
+++ b/scripts/U-01
@@ -5,11 +5,24 @@
 # uname + case 사용
 
 case "$(uname -s)" in
-    Linux*) dist = $(lsb_release -a | grep Distributor | awk -F" " '{print $3}')
-    if [$dist == "Ubuntu"|"Debian"]; then
+    Linux*) 
+    if [[ -f /etc/os-release ]]; then
+        dist=$(grep "^ID=" /etc/os-release | awk -F= '{print $2}')
+    else
+        echo "Distribution could not be identified."
+        exit 1
+    fi
     
+    if [[ $dist = "Ubuntu" || "Debian" ]]; then
+        echo "cat /etc/pam.d/login | grep pam_securetty.so"
+        echo "cat /etc/securetty | grep pts/*"
+    fi
+    if [ $dist = "CentOS" || "Redhat" ]; then
+        echo "cat /etc/pam.d/login | grep pam_securetty.so"
+        echo "cat /etc/securetty | grep pts/*"
+    fi
     ;;
-    AIX*)
+    AIX*) if 
 
 # 2. SSH 설정 파일 확인
 # if [ -f ] 구문 사용
